name: CI
on:
  push:
    branches: ['main']
  workflow_dispatch:
env:
  REACT_APP_ISSUE_TOKEN: ${{secrets.REACT_APP_ISSUE_TOKEN}} ## ※1
jobs:
  deploy:
      runs-on: self-hosted
  
  strategy: 
      matrix:
          node-version: [18.x]
          
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: gh-pages -d build
