name: NodeJS with Webpack
permissions:
  actions: write # Necessary to cancel workflow executions
  checks: write # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  REACT_APP_ISSUE_TOKEN: ${{secrets.REACT_APP_ISSUE_TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.REACT_APP_ISSUE_TOKEN }}


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        ls
        echo process.env.REACT_APP_ISSUE_TOKEN
        echo ${{ secrets.REACT_APP_ISSUE_TOKEN }}
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.REACT_APP_ISSUE_TOKEN }}
        folder: build # The folder the action should deploy.